version: '3.7'

services:

  #MySQL Database 
  mysql-database: 
    container_name: mysql-book
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: book
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db-file:/var/lib/mysql
            
  #Prometheus for capture metrics    
  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus_book
     volumes:
     - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
     command:
     - "--config.file=/etc/prometheus/prometheus.yml"
     ports:
     - 9090:9090  
     
  #Grafana for diplay graphics 
  grafana:
     image: grafana/grafana:latest
     container_name: grafana_book
     ports:
     - 3000:3000
      
# Names our volume
volumes:
  mysql-db-file: